version: "3.8"

services:
  # server:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile

  #   command: /bin/bash /path/to/run.sh
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - DB_HOST=mysql
  #     - DB_PORT=3306
  #     - DB_USERNAME=root
  #     - DB_PASSWORD=root_password
  #     - DB_DATABASE=arte_arena
  #   depends_on:
  #     - mysql
  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   environment:
  #     - NODE_ENV=production
  #   ports:
  #     - "3000:3000"

  mongodb:
    image: mongo:6.0
    container_name: db_mongodb_bhut
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_password
      MONGO_INITDB_DATABASE: bhut
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_bhut
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
volumes:
  mongo_data:
